jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Install dependencies
      run: yarn install --frozen-lockfile --non-interactive
    - continue-on-error: true
      name: Lint
      run: yarn run lint
    - continue-on-error: true
      name: Test
      run: yarn run test
    strategy:
      matrix:
        node-version:
        - 10
name: react-native-app-auth CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
