jobs:
  release:
    name: Release
    permissions:
      contents: write
      deployments: write
      id-token: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - continue-on-error: true
      name: Install dependencies
      run: yarn install --frozen-lockfile
    - continue-on-error: true
      name: Unit Tests
      run: yarn test
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      id: changesets
      name: PR or Publish
      uses: changesets/action@v1
      with:
        publish: yarn changeset publish
        version: yarn changeset version
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
